# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb00c1034420addb98fce050685822ed5b352cbdb92e105155e049b1ee8db75d9470e8c83ef7298403454638f2f27b9867523571728a1c98504690abfd50036

test:
  secret_key_base: da906c59371e7b7889d972c4298ab6c8dd47fafe9684d32b1909d919b661c2db241548873dfd2fecb9bc10392ecee6429ee1783e3d196592fc27693ee30c1572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
